### PR TITLE
Update for new WebXRProtocol

### PR DESCRIPTION
**Pull request by vasil-ok**

### CODE REVIEW

**Comment by TrevorFSmith** [comment]
@vasil-ok Have you tested all of the example apps linked from the initial web page to see if they work with the new protocol?

**Comment by vasil-ok** [comment]
All examples have tested with JS for - https://github.com/mozilla/webxr-polyfill/pull/31. Also fixed project settings for new name - XRViewer.

**Comment by TrevorFSmith** [comment]
Ok, I've created a 'develop' branch where we'll work from now on. Please set this PR for that branch and then merge it there.

**Comment by vasil-ok** [comment]
move to https://github.com/mozilla-mobile/webxr-ios/pull/17

**Pull request closed without merging**
