### PR TITLE
update style of index page and add screenshots

### PR DESCRIPTION
**Pull request by joshmarinacci**

### CODE REVIEW

**Comment by blairmacintyre** [comment]
@TrevorFSmith if this is ok, I'd like to pull this into master and merge down into develop.  We don't want to pull all of develop into master right now (there are changes that need an app update in iTunes, I think?), but I'd like to get the website to be nicer.

**Comment by TrevorFSmith** [comment]
Ok, I'll double check it now and assuming everything looks fine I'll merge it into master.

**Comment by TrevorFSmith** [comment]
@joshmarinacci The page looks good! The only thing I see is that when I load the page in the WenXR Viewer, it won't scroll down to show the bottom-most bit of the second row of examples (see attached image). Once that's fixed, go ahead and merge this PR into master.

img_18b0f818bf20-1

**Comment by joshmarinacci** [comment]
Hmm. I'm not sure what the ultimate cause is off the scrolling issue.  It looks fine in a regular browser on my ios device.  Anyway, I added some extra padding to the bottom of the page. See if that fixes it.

**Pull request merged**
